title = "Steve Lyskawa LLC" 
baseURL = "http://localhost"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "themes/"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "description in config.toml"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #background_color_class = "bg-blue"
  featured_image = "/images/sunset.jpg"
